language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
ruby: 2.2.0
before_install:
- date
- locale
- echo $PATH
- sudo apt-get install libprotobuf-dev protobuf-compiler libc-ares2 libleveldb-dev -y
script:
- make test
- make
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - leoxiang727@gmail.com
env:
  global:
  - LANG="en_US.UTF-8"
